### ISSUE TITLE
Buildmaster does not do implicit dependency solving within a run

### ISSUE THREAD

**Issue by waddlesplash** [haikuports/haikuporter#158]
e.g. https://kitchen.haiku-os.org/master/x86_gcc2/?buildrunDir=880&viewMode=expanded : the iconv build needed the updated libtool, but it didn't bother to solve (or even run one after the other)

In a more harmful case, see the end of https://buildbot.haiku-os.org/builders/haiku-master-x86_gcc2_hybrid/builds/4172/steps/jam%20%40release-raw/logs/stdio : 
```
Encountered problems:
problem 1: nothing provides lib:libhalf>=12.0.0 needed by openexr-2.2.1-1
  solution 1:
    - allow deinstallation of openexr-2.2.1-1
```

12.0.0 is the libversion of the previous version of ilmbase, and ilmbase and openexr were upgraded in the same run, but it didn't implicitly solve so now we have an openexr incompatible with the ilmbase in the repos.

**Comment by mmlr** [comment]
I said it before and I'll say it again: If something isn't marked to depend on some specific version and the previous version satisfies the requires at the time of solving, then the previous version is just as valid a match as the next one to be built.

Relying on the presence or absence of a certain package or provides to avoid explicitly declaring a requirement is just not valid. There should simply not be any implicit dependecies.

For the case of libhalf, if the new version of libhalf is compatible with the 12 version, then it should simply state that fact with a compat declaration. If openexr depends on a specific ilmbase, it should equally declare that explicitly.

With these explicit declarations the packages will be built as needed and in the needed order.

**Comment by waddlesplash** [comment]
> If openexr depends on a specific ilmbase, it should equally declare that explicitly.

You misread my initial post: it **doesn't** depend on a specific ilmbase, but the two versions of ilmbase are incompatible. Buildmaster built the new openexr against the old ilmbase in the same run that a new, **binary-incompatible** ilmbase was built. ***That*** is the problem I'm blaming buildmaster for.

**Comment by mmlr** [comment]
I did not misread it, I'm just disputing the validity of the outcome you describe as expected.

For one, the recipes were merged sequentially by separate actions (19 seconds apart if the notifications are to be trusted). That they ended up in the same buildrun is completely arbitrary.

Depending on the fact that a certain state of the HaikuPorts tree plus random pre-existing packages fit together, and that this state is recorded into the packages by the implicit requires update, is just not a proper way to manage the package repository. If it was, we could just as well spare ourselves the whole requires/provides overhead and just try to keep HaikuPorts in a valid state manually by timing updates in a certain order.

The problem in this case is precisely that openexr isn't declared to depend on a specific version and/or that the ilmbase versions are not declared as compatible. These missing explicit declarations make the outcome arbitrary. Just bumping the revision afterwards does not help robustness of the package repository either. It may work to just rebuild the packages, but it works for the wrong reason, i.e. because of a certain state of existing packages, not because it is properly declared.

Cases like these happen from time to time and they need to be looked at individually. In the case of ilmbase, the change of the major version was purely cosmetic. So the ilmbase would actually be fully compatible with the old version. It could therefore be declared as such (a compatibility symlink with the old major version may also be needed). The change was arguably not planned very well and we're not the only ones affected, see https://github.com/openexr/openexr/issues/250.

Alternatively this could be treated as an actual new major version release and the same procedure for major version changes could be followed as with other libraries, i.e. start providing ilmbase23 for the new major version analogous to libpng12, 15, 16 etc. This would have the benefit of not breaking stuff that may use ilmbase outside of HaikuPorts. In this case that would obviously be a bad idea, as the release that brought the version change was mixed with security fixes and the old version is not going to be maintained anymore.

A major version release is usually major and it is expected that some things may need to be reevaluated. The libpng example demonstrates this. You can't just update an unsuffixed libpng with a new major version (which usually implies ABI and API breakage), and then rely on buildmaster to just blindly rebuild everything against that. Many things would break, just because the libraries wouldn't actually be source or binary compatible. That is why we have the suffixed libpng versions and then explicitly mark certain recipes to depend on a specific one, because the maintainer/porter has determined that it is compatible with that version.

That ilmbase isn't actually incompatible in this very specific case is pure coincidence and can't be expected of a major version bump. In the general case, someone bumping a library recipe to a new major version will have to do at least some (and maybe a lot of) work to anticipate and validate the outcome and then take appropriate action, for example by splitting/maintaining multiple library version and adjusting depending ports to require a compatible one.

Then there's the other buildrun you point at. In the first sentence of this issue you say:

> the iconv build needed the updated libtool

I'm sorry but it doesn't get more obvious than that. If iconv needs a specific libtool version, then this simply must be declared in its requires. Anything less is just arbitrary and invalid.

This also doesn't just affect the package repository at vmpkg that the buildmaster is concerned with. If dependencies are left undeclared things may work in that repository due to the state it happens to be in, but the state would not be reproducible. If someone were to clone HaikuPorts and try to build that iconv version it may very well just fail, depending on what packages are installed on that system.

Declaring dependencies properly and explicitly is really the only way to have a robust, reproducible package repository. I can't really say more on the issue than that. It is also what the requirements guidelines state (at the very bottom, and no I didn't just put that in there): https://github.com/haikuports/haikuports/wiki/HaikuPorter-HandlingRequirements

**Comment by waddlesplash** [comment]
> It may work to just rebuild the packages, but it works for the wrong reason, i.e. because of a certain state of existing packages, not because it is properly declared.

I'm not sure I agree here. The SONAMEs are different, and the ABI has changed, yes; but source compatibility was preserved, and so the HaikuPorts tree itself is in a consistent state, only the pre-built packages are not.

Recently, FFmpeg was bumped, which was a perfect example of an upgrade that completely broke ABI while also preserving source compatibility. None of these recipes in the tree depend on one FFmpeg version or the other, and FFmpeg itself is certainly not "compat"-ible, and so I had to merge the FFmpeg recipe first and then push a "bump revisions of dependencies" afterwards due to this ticket.

What else could have been done here? Again, the HaikuPorts tree was in a consistent state either way, only the generated packages were not.

**Comment by pulkomandy** [comment]
We don't really have a choice here. The package hrev needs to be bumped for a rebuild anyways. While doing so, one may as well add the abi version constraint to the recipe, meaning "I want this recipe to be built with this version of ffmpeg".And it will help us tracking what was updated, and what wasn't.

And in any case, replacing a package with an abi incompatible one should not be allowed, so in the first place the new package should have been named ffmpeg4. In a Debian like world this would not be needed, but we support 3rd party repo and they should be able to depend on our packages. You can't coordinate an update with them, so you should make sure compatibility is kept.

So, there will be multiple ffmpeg versions around, and the only way for recipes to tell which one they are tested with is using a version constraint.

**Comment by waddlesplash** [comment]
Closing in favor of #164.
