### ISSUE TITLE
File exists error during bash bootstrap

### ISSUE THREAD

**Issue by kallisti5** [haikuports/haikuporter#163]
During unpack of bash bootstrap sources, we see "File exists":

```
Skipping checksum validation of bash44-021
Skipping download of source for bash44-022
Skipping checksum validation of bash44-022
Skipping download of source for bash44-023
Skipping checksum validation of bash44-023
Skipping unpack of bash-4.4.tar.gz
Unpacking source of bash44-001
[Errno 17] File exists: '/home/alex.vongluck/Code/haiku/generated.arm/objects/haiku/arm/packaging/repositories/HaikuPortsCross-build/app-shells/bash_bootstrap/work-4.4.023/sources-001'
```

**Comment by kallisti5** [comment]
I can confirm that reverting 71f2d2253310512e108567f1d29fba66bda9bafa solves it.  @pulkomandy

**Comment by kallisti5** [comment]
sources-001 is a directory (contrary to Python's horrible error messages)
Removing it, and rebuilding results in the same error (and the directory being re-created prior to the error)

**Comment by pulkomandy** [comment]
Actually the message would be more useful if it was a backtrace from Python. The current one is probably from some command run by shutil.

The point of 71f2d22 is to create the directory, so that whe, you "unpack" a #noarchive, it is extracted inside the directory, not in place of it. If you have a better fix, make sure it doesn't break the ca_root_certificates recipe (where the file otherwise got extracted with the name "sources" and then we got "sources: not a directory" when trying to use it).
