### ISSUE TITLE
--missing-dependencies & --get-dependencies one and the same.

### ISSUE THREAD

**Issue by khallebal** [haikuports/haikuporter#172]
Hi,
The option --missing-dependencies doesn't do what it says:
```python
 `build missing direct and indirect dependencies, then build the port`
```

Instead it tries to install from repository, hence the title.

**Comment by mmlr** [comment]
The only place where dependencies are installed via pkgman is here:

https://github.com/haikuports/haikuporter/blob/b0f8ba3f116c235b802102f5f7f7f9179bcfba00/HaikuPorter/DependencyResolver.py#L237

And it can only happen when the getDependencies option is set. So I don't see how that would be possible. Can you provide more details like the output of an actual build that exhibits that behaviour?

The getDependencies mode is only enabled in one place, when parsing command line options. Are you using an alias to run HaikuPorter that includes that command line switch?

Since getDependencies hooks into the dependency resolution and installs packages whenever a dependency is missing, it will bypass all of the actual dependency modes (all, update, missing) since the "dependency missing, how to handle?" step is never reached. So if both get and missingDependencies (or any of the other modes) are specified at the command line, getDependencies will trigger first.

**Comment by khallebal** [comment]
> Are you using an alias to run HaikuPorter that includes that command line switch?

Yes, that's indeed the case, but i thought that manually set options had precedence over the ones set in an alias!, doesn't that seem more logical?

**Comment by waddlesplash** [comment]
Aliases are done by `bash`, HaikuPorter has no possible way of telling the difference between options from the alias and actual options.
