### ISSUE TITLE
Buildmaster can get stuck on "waiting for build package xxx to be activated"

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuporter#233]
(Opening this one per @pulkomandy's suggestion)

This happened yesterday, for example. The buildmaster for x86_64 got stuck for several hours. See the logs here:

https://build.haiku-os.org/buildmaster/master/x86_64/?buildrunDir=7500&viewMode=expanded [77818.log, 3.0 MB]

`waiting for build package havoc-0.2.0-1 to be activated` got repeated almost 56000 times

until a final: 

    command exit status: -1
    build failed: builder disconnected

@Begasus mentioned on IRC that he has seen similar, but usually on 32 bits (but I'm not sure if he meant the hangs on the buildmaster, or the same type of error on his 32 bits local builds, as in #207, perhaps).

**Comment by mmlr** [comment]
It was a package_daemon issue, so a Haiku bug. A heap corruption occured, one of the job runner threads asserted with "getNumAvailable()...". The Debugger apparently failed to create a debug report as it was stuck creating the stack trace when I looked into it, so there's only the mentioned debug reason to go by.

We could try running package_daemon with the guarded heap on the builders as they heavily exercise it. But due to the limited RAM this probably wouldn't work very well.

**Comment by mmlr** [comment]
It was again a package_daemon crash that then hung the Debugger when it tried to save a debug report. This time a job runner thread had a segfault. There may be something in the current set of packages that triggers this, as this has never been observed before.

Apparently someone aborted the job on the buildmaster side so that a parallel one was running as well. Since the package daemon failed, that obviously got stuck the same way as the first one. If the Debugger wouldn't hang, the system would restart the package_daemon, which may or may not allow to run further builds. The one running at the time of the crash would definitely continue to hang, as the activation command will be lost and never complete.

I do not know why the Debugger hangs, maybe it tries to do package lookup for symbol resolution? But in the non-interactive "save report" mode, it probably shouldn't as it wouldn't be able to ask for installing packages anyway.

The builder has been rebooted, it will run the outstanding builds once a new commit is made on the HaikuPorts side.

**Comment by Begasus** [comment]
Seems another failure now on both 32bit and 64bit, did something changed at the buildmaster?
```
Warning: failure creating the build package:
Error: Build has failed - stopping.
```

**Comment by mmlr** [comment]
> The new buld run, 7598, seems to be hang again on the same repeating "waiting for build package wireshark-4.0.1-1 to be activated".

It is the same as before, a package_daemon crash. I spent some time to look into it and reproduce the case with the guarded heap and it shows that there is indeed a bug somewhere in package_daemon that corrupts memory. As with all memory corruption, when run in a normal system the effect will not always show, that is why it sometimes works for a couple of builds and then falls into the same problem again. As to why this now happens more regularly, I don't know but assume that it is tied to some packages that are now used as dependencies and exercise features that previously weren't. Or it may have always been a problem but it becomes more likely to show due to the amount of packages or their properties.

> Seems another failure now on both 32bit and 64bit, did something changed at the buildmaster?

The build infrastructure is in the process of being prepared for the new Haiku release. That means both the buildmaster side will be repopulated with a new set of initial packages and the builders will be updated to a newer Haiku revision. The builders were stuck at an old revision previously due to a change in the syscall interface that wouldn't have allowed to keep building beta 3 packages. @kallisti5 is doing that migration and I don't know the exact timeline there.

**Comment by kallisti5** [comment]
The r1beta4 build-packages were loaded into the system-packages for haikuporter this evening.  Any build going forward should work as expected.

**Comment by Begasus** [comment]
@kallisti5 Thanks! First packages already build fine :+1:

**Comment by kallisti5** [comment]
This one hasn't come up in a while. I'm going to go ahead and resolve it for now.
