### ISSUE TITLE
Explicitly state which dependency could not be satisfied (or why)

### ISSUE THREAD

**Issue by OscarL** [haikuports/haikuporter#256]
While trying to build "opencolorio-2.0.1" on beta4, 32 bits (x86), I get:

```
Fetching package for devel:libboost_system_x86 >= 1.70.0 ...
Fetching package for devel:libglew_x86 >= 2.2 ...
Error: unable to resolve required packages for build for opencolorio_x86-2.0.1
Error:  dependency-infos:
Error:          /boot/home/SourceCode/haikuports/haikuports/repository/opencolorio_x86-2.0.1.DependencyInfo
Error:          /boot/home/SourceCode/haikuports/haikuports/repository/opencolorio_x86_devel-2.0.1.DependencyInfo
Error:  repositories:
Error:          ['/boot/home/SourceCode/haikuports/haikuports/packages', '/boot/system/packages']
Error: 
```

It would be nice if the package that failed to be found/install was more clearly stated, instead of having to do a manual pkgman search for each of the dependencies.

**Comment by Begasus** [comment]
pkgman already knows the (suggested) sollution, isn't there a way to pass this information through to haikuporter.

**Comment by coolcoder613eb** [comment]
I would like to contribute, can you help me get started?

**Comment by Begasus** [comment]
Not an export on the matter here, maybe @OscarL can give a more clear answer, but here it goes:
If 2 packages conflict with each other pkgman (our package manager) knows about it and will give a suggestion on wether you like to uninstall the cnflicting package to be able to use the package you need (in the above example, remove devel:libglew1 and install devel:libglew >= 2.2, or quit.
haikuporter, our tool to create the packages receive a request for a specific version for libglew, but doesn't know how to solve it, the idea here is now to tell haikuporter to somehow "find" the conflict and inform the user about that conflict instead of producing an output like: `error: unable to resolve required packages for build for opencolorio_x86-2.0.1` which is rather useless as it doesn't say what the actual problem is.
