### ISSUE TITLE
HP doesn't create the DependencyInfo for the requested recipe version

### ISSUE THREAD

**Issue by humdingerb** [haikuports/haikuporter#69]
As example, look at cdrtools. There are recipes for old alpha versions (~a27 to ~a31) and the final version:
> cdrtools-3.01.recipe
> cdrtools-3.01~a27.recipe
> cdrtools-3.01~a29.recipe
> cdrtools-3.01~a30.recipe
> cdrtools-3.01~a31.recipe

Doing a "haikuporter cdrtools" will build the last alpha (cdrtools-3.01~a31).
Doing a "hakuporter cdrtools-3.01" tries to build the final, but stops with
```
[Errno -2147459069] No such file or directory:
'/HiQ-Data/sources/haikuports/repository/cdrtools-3.01.DependencyInfo'
```
Looking into the repository folder, I see that the DependencyInfo files for cdrtools-3.01~a31 are generated instead. The same happens if I try to build any other version of cdrtools.

Related to #47 ?

**Comment by DarkmatterVale** [comment]
I'm having a very difficult time replicating this issue. I have gotten a similar error in the past when I was writing libraries, but it is very inconsistent.

Is anyone able to reproduce this error *consistently*?

**Comment by humdingerb** [comment]
Just stick with the cdrtools example. There are currently 2 recipes: cdrtools-3.01.recipe and cdrtools-3.02~a05.recipe. Try building with "hp cdrtools-3.01" and it fails with "[Errno -2147459069] No such file or directory: '/Source-Ports/haikuports/repository/cdrtools-3.01.DependencyInfo'".   
In the "repository" folder only "cdrtools-3.02~a05.DependencyInfo" is created, not one for the older cdrtools-3.01.

**Comment by DarkmatterVale** [comment]
After experimenting, I have figured a couple of interesting things out. First off, this is definitely related to #47 and is in fact just a specific example of that issue. Second, HaikuPorter is indeed gathering the dependency info for the specified version (in this case 3.01). The issue is that there is some statement somewhere in the code that is making HaikuPorter exit the process mid way, causing the dependency info file to never be never be created.

I am trying to find this code, but it is pretty difficult...

**Comment by phoudoin** [comment]
Some uncatched exception, maybe?
